spring:
  datasource:
    url: jdbc:postgresql://${db-url:localhost}:5432/testjava
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  application:
    name: test-java

# Actuator Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: "health,beans,metrics"
      base-path: "/test-java"

  endpoint:
    health:
      show-details: always




